### PR TITLE
update for latest ensembl GTFs

### PR DESCRIPTION
**Pull request by brentp**
without this, samplot breaks on recent ensembl GFFs

### CODE REVIEW

**Comment by brentp** [comment]
here's the view without whitespace changes, my editor strips trailing spaces:
https://github.com/ryanlayer/samplot/pull/68/files?w=1

**Comment by brentp** [comment]
well, this doesn't actually fix the problem as samplot appears to handle only BED format. Is that so?

**Comment by brentp** [comment]
this is ready for review/merge. new ensembl GTFs no longer contain `transcript` features, only `mRNA` so this is required.

**Comment by ryanlayer** [comment]
Thanks, I fixed this in the latest release.

**Pull request closed without merging**
